grid-columns: 5
direction: down

Input: {
  grid-columns: 1
  Investment universe
  Potential clients
}

Expected Return: {
  grid-columns: 1
  Current Valuation
}

Risk: {
  Concentration
  Scenario analysis
}

Expert Judgement: {
  grid-columns: 1
  Asset allocation
  Macro outlook
  Industry outlook
}

Client Preferences: {
  grid-columns: 1
  Demographics (Life stage)
  Risk tolerance
  Investment experience
  Tax considerations
}

Goal and objectives: {
  grid-columns: 1
  Investment horizon
  Liquidity needs
  Certainty of cash flows
}
