grid-columns: 5
direction: down

Input: {
  grid-columns: 1
  Investment universe
  Asset allocation
  Expected return
  Risk
  Expert judgement
  Client preferences
  Goal and objectives
}

Expected Return: {
  grid-columns: 1
  Market Sentiment
  Current Valuation
}

Risk: {
  Concentration
}

Expert Judgement: {

}

Client Preferences: {
  grid-columns: 1
  Demographics (Life stage)
  Risk tolerance
  Investment experience
  Tax considerations
}

Goal and objectives: {
  grid-columns: 1
  Investment horizon
  Liquidity needs
  Certainty of cash flows
}
