grid-columns: 3

Product: |md
    ## Product
    - Asset class
    - Risk rating
    - Historical performance
    - Expected return
    - Volatility
    - Liquidity
    - Certainty (1y, 3y, 7y)
|
product.shape: parallelogram

prr: |md
    ## Product Risk Rating
    Followings are considered:
    - Market risk
    - Liquidity
    - Leverage
    - Drawdown
    - Complexity and other risk metrics
|
prr.shape: page
prr.style.fill: linen

product -- prr

holding: |md
    ## Client Portfolio
|
holding.shape: parallelogram

cpm: |md
    ## Client-Product Matching 
    - Client risk rating >= product risk rating
    - Product fit to client needs using 4 dimensions
        - Expected return
        - Volatility
        - Liquidity
        - Time horizon
    - Macro economic trend
        - Interest rate
        - Sector rotation
        - Geographic focus
|
cpm.shape: rectangle
cpm.style.fill: deepskyblue

pfa: |md
    Product-fit analysis  
     (Top 10 clients)
    -------------------    
    List of top 10 clients with best buying score.
|
pfa.shape: parallelogram
pfa.style.fill: honeydew

holding -> cpm

Client: |md
    ## Client
    - ID
    - Demographic
    - Risk profile
        - Rating
|
client.shape: parallelogram

product -- holding -- client

need_id: |md
    ## Needs identifier
    Identify client needs based on demographic information
|
need_id.shape: rectangle
need_id.style.fill: deepskyblue
# darkseagreen

Needs: |md
    ## Needs
    Retirement, University Funding, Down payment
    - Historical performance
    - Expected Return
    - Liquidity
    - Time horizon
|
needs.shape: parallelogram
needs.style.fill: honeydew

client -> cpm
product -> cpm
Client -> need_id -> Needs -> cpm
cpm -> pfa
