direction: down
grid-rows: 5
grid-columns: 3
# grid-gap: 80

client_db -> irs -> potential_client
product_db -> selected_products -> pc_matcher.pfs
potential_client -> pc_matcher.pfs

selected_products: |md
    ## Selected Products
    - RM select on UI
    - Bank's promotion
    - Top selling products
|
selected_products.shape: document

client_db: |md
    ## Client Database
    - Age
    - Gender
    - Married
    - Tax Residence
    - Income
    - Investment goals (TBD)
    - Holdings
|
client_db.shape: stored_data

potential_client: |md
    ## Top-n Selected Clients
    - Readiness Score
|
potential_client.shape: document

product_db: |md
    ## Products Catalog
    - Asset class
    - Risk rating
    - Liquidity
    - Historical performance
        - Expected return
        - Volatility
        - Max drawdown
    - Complexity and other risk metrics
    - Natural language comment
    width: 500
|
product_db.shape: stored_data

irs: |md
    ## Investor Readiness Scorecard
    - % Cash or equivalents
    - Concentration Risk
    - Investment experience
    - Life stage (Number of potential needs)
|
irs.shape: step
irs.style.fill: linen

pc_matcher: AI-assist product-client matcher {
    direction: down

    pfs: |md
        ## Product Fitness Scorecard
        - Risk Rating
        - Incremental Concentration Risk
        - Better Product than Current Holding
        - Investment experience
    |
    pfs.shape: step
    pfs.style.fill: linen

    matching_scores: |md
        ## Matching Scores
        - (client1, product1, score 1)
        - (client1, product2, score 2)
        - (client2, product1, score 3)
    |

    matching_scores.shape: rectangle

    market: |md
        # Market Outlook
        - Bank's Research
        - News and Market Sentiment
    |
    market.shape: rectangle

    scenario: |md
        # Scenario Analysis Engine
        - Selected historical period
    |
    scenario.shape: rectangle

    llm: |md
        ## AI assisted proposal generation
        - Pick the best product for each client based on the product/investor fitness score & market outlook.
        - Compose proposal with natural language
        - Scenario Analysis
    |
    llm.shape: rectangle

    proposal: Proposal

    pfs -> matching_scores
    market -> llm
    matching_scores -> llm
    scenario -> llm
    llm -> proposal
}

