output_filename: runs/market_data/selected_etf.csv
metrics:
  - return
  - CAGR
  - max_drawdown
  - calmar_ratio
frequency: 1w
periods:
  - 6m
  - 1y
  - 3y
  - 5y
  - 10y
name_preference: long
tickers:
  - XLK
  - XLF
  - XLV
  - XLY
  - XLP
  - XLE
  - XLI
  - XLB
  - XLRE
  - XLU
  - XLC
  - VOO
  - HYG
  - FLOT
  - BSV
  - SHYG
  - USO
  - GLDM
  - CBON
  - ICVT